### ISSUE TITLE
List of key organisations and people within them who would be users/suppliers of data

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/manchester-data-use-pilot#3]
This deliverable is an ongoing deliverable of identifying stakeholders that are relevant for the pilot and 360Giving.

**Comment by Julianlstar** [comment]
This is held within Client Contacts broken down into Type of organisation, Contact details and Contact type. [https://docs.google.com/spreadsheets/d/1i4YIyMzQY6JEsupnbN_EHGqhZP1w9MxnKiaSFBVzNQM/edit?usp=sharing](url)

**Comment by morchickit** [comment]
Mor to add the contact to the CRM and open a new issue about it.  @Julianlstar to add the status of each contact at the end of the project.

**Comment by morchickit** [comment]
@Julianlstar to create tab of publishers he works with so I can move it to the CRM.
