### ISSUE TITLE
Series of meetings with individuals and organisations

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/manchester-data-use-pilot#5]

**Comment by Julianlstar** [comment]
This is ongoing and progress is mapped in within the Client Contact https://docs.google.com/spreadsheets/d/1i4YIyMzQY6JEsupnbN_EHGqhZP1w9MxnKiaSFBVzNQM/edit?usp=sharing

**Comment by morchickit** [comment]
Julian did many of them!
