### ISSUE TITLE
Delivery of 3 workshops (minimum) promoting and explaining the use of 360Giving

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/manchester-data-use-pilot#6]

**Comment by Julianlstar** [comment]
Four workshops were delivered at the end of April and beginning of June for Housing Associations, Charitable Trusts and Foundations, Local Authorities and Voluntary Sector. There is also an additional workshop that is happening on the 19th June

**Comment by morchickit** [comment]
Done!
