### ISSUE TITLE
End of project report

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/manchester-data-use-pilot#9]
Report should consist - 

- What we tried to achieve? 
- What worked well and why ? 
- What worked bad and why?
- Recommendation for future pilot and recommendations of what to do in the future in Manchester and 360Giving.

**Comment by Julianlstar** [comment]
There is uncertainty as to what this will be. It could be a write up of learnings of which there is a few.

**Comment by Julianlstar** [comment]
Comments have been incorporated and additional information included
